@extends('layouts.app')
@section('title', 'แปลงยาว')
@section('content')
    @include('pages.home.components.section-1')
    @include('pages.home.components.section-2')
    @include('pages.home.components.section-3')
    @include('pages.home.components.section-4')
    @include('pages.home.components.section-5')
    @include('pages.home.components.section-6')
@endsection
